I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 126, in script
    show sean neutral with Dissolve(0.2)
Exception: Image 'sean' does not accept attributes 'neutral'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 126, in script
    show sean neutral with Dissolve(0.2)
  File "C:\Users\Felicity\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Felicity\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Felicity\Desktop\renpy-8.0.3-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Felicity\Desktop\renpy-8.0.3-sdk\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Felicity\Desktop\renpy-8.0.3-sdk\renpy\display\transform.py", line 881, in _duplicate
    args.extraneous()
  File "C:\Users\Felicity\Desktop\renpy-8.0.3-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'sean' does not accept attributes 'neutral'.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
mainmenutesting 1.0
Sun Mar 26 23:34:57 2023
